### ISSUE TITLE
rename plugin

### ISSUE THREAD

**Issue by ezio416** [SCDevel/BetterMapHistoryTM#1]
Hi, I can't find you on discord so I'll open an issue here. I'm the developer for the Map History plugin, and while I don't care if you use my idea and make it "better" (even though this one only supports tmx maps, kinda limiting), I'd appreciate if you don't give it the exact same name as mine. This will just cause confusion. You use the identifier `BetterMapHistory`, so please call the plugin that or TMX Map History or something. Thank you!

**Comment by SCDevel** [comment]
I would first like to apologize I did originally search for a "Map History" plugin and could not find anything (not sure why).
I used "Better" just because "MapHistory" and assumed it was some dead plugin (because I could not find it) no real meaning to it at all. just needed something else. anyway I have changed the name to "TMX Map History". again, sorry.

**Comment by ezio416** [comment]
No worries, thank you! Not dead, this is still maintained lol https://openplanet.dev/plugin/maphistory
